language: haskell
ghc: 7.8
before_install:
  # install LXC headers
  - sudo apt-get install software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-lxc/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y lxc-dev
  # install trass-config
  - git clone https://github.com/trass/trass-config.git
  - cd trass-config
  - cabal install
  - cd ..
  # install trass-vm
  - git clone https://github.com/trass/trass-vm.git
  - cd trass-vm
  - cabal install
  - cd ..
