language: haskell
ghc: 7.8
before_install:
  # install LXC headers
  - sudo apt-get install software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-lxc/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y lxc-dev
    # get trass-config and trass-vm from sources
  - git clone https://github.com/trass/trass-config.git
  - git clone https://github.com/trass/trass-vm.git
  - cabal install trass-config/ trass-vm/
